#
# football-players service, exposed to public (type = LoadBalancer)
#
apiVersion: v1
kind: Service
metadata:
  name: football-players
  labels:
    app: football-players
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
  selector:
    app: football-players

---

#
# Autoscaler setup for the football-players service
#
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: football-players
spec:
  scaleTargetRef:
    kind: Deployment
    name: football-players
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50

---

#
# Deployment for the football-players service
#
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: football-players
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: football-players
  template:
    metadata:
      labels:
        app: football-players
        version: v0.0.1
        tier: backend
    spec:
      containers:
      - image: gcr.io/${GCLOUD_PROJECT}/football-players:v0.0.1
        name: football-players
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 50m
            memory: 1Gi
          requests:
            cpu: 25m
            memory: 512Mi
